// -----------------------------------------------------------------------------
// <auto-generated>
//     This file contains the bootstrap logic for the TomatoNovel API.
//     It configures middleware, OpenAPI documentation, EF Core, OpenIddict
//     authentication/authorization, dependency injection and global services.
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using OpenIddict.Abstractions;
using OpenIddict.Validation.AspNetCore;
using Scalar.AspNetCore;

using TomatoNovel.Api.Middlewares;
using TomatoNovel.Application.Interfaces;
using TomatoNovel.Application.Services;
using TomatoNovel.Domain.Interfaces;
using TomatoNovel.Infrastructure.Persistence;
using TomatoNovel.Infrastructure.Repositories;

var builder = WebApplication.CreateBuilder(args);

// -----------------------------------------------------------------------------
// MVC Controllers
// -----------------------------------------------------------------------------

/// <summary>
/// Registers controller-based routing.
/// </summary>
builder.Services.AddControllers();

// -----------------------------------------------------------------------------
// CORS
// -----------------------------------------------------------------------------

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy
            .WithOrigins("http://localhost:5173")
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});

/// <summary>
/// Registers IHttpContextAccessor for accessing the current HttpContext.
/// Required by OpenIddictTokenService.
/// </summary>
builder.Services.AddHttpContextAccessor();

// -----------------------------------------------------------------------------
// OpenAPI (Swagger) - New .NET 9 OpenAPI System
// -----------------------------------------------------------------------------

/// <summary>
/// Registers the new .NET 9 OpenAPI + JWT Bearer security.
/// </summary>
builder.Services.AddOpenApi(options =>
{
    options.AddDocumentTransformer((document, context, ct) =>
    {
        document.Components ??= new OpenApiComponents();

        document.Components.SecuritySchemes["Bearer"] = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "JWT"
        };

        document.SecurityRequirements.Add(
            new OpenApiSecurityRequirement
            {
                [
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference
                        {
                            Type = ReferenceType.SecurityScheme,
                            Id = "Bearer"
                        }
                    }
                ] = new List<string>()
            });

        return Task.CompletedTask;
    });
});

// -----------------------------------------------------------------------------
// Database Configuration (EF Core + MySQL)
// -----------------------------------------------------------------------------

/// <summary>
/// Gets connection string from configuration.
/// </summary>
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException(
        "Connection string 'DefaultConnection' was not found.");

/// <summary>
/// Registers EF Core DbContext and OpenIddict stores.
/// </summary>
builder.Services.AddDbContext<TomatoNovelDbContext>(options =>
{
    options.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString));
    options.UseOpenIddict();
});

// -----------------------------------------------------------------------------
// OpenIddict Authentication / Authorization
// -----------------------------------------------------------------------------

/// <summary>
/// Configures OpenIddict core, server, validation services.
/// </summary>
builder.Services.AddOpenIddict()
    .AddCore(options =>
    {
        options.UseEntityFrameworkCore()
            .UseDbContext<TomatoNovelDbContext>();
    })
    .AddServer(options =>
    {
        options.SetTokenEndpointUris("/connect/token");

        options.AllowPasswordFlow();
        options.AllowRefreshTokenFlow();

        // Register standard and custom scopes
        options.RegisterScopes(
            OpenIddictConstants.Scopes.OpenId,
            OpenIddictConstants.Scopes.OfflineAccess,
            "onlinestudy_api.read",
            "onlinestudy_api.write"
        );

        // Development signing / encryption keys
        options.AddEphemeralEncryptionKey()
            .AddEphemeralSigningKey()
            .DisableAccessTokenEncryption();

        // Allow public (anonymous) OAuth clients
        options.AcceptAnonymousClients();

        options.UseAspNetCore()
            .EnableTokenEndpointPassthrough();
    })
    .AddValidation(options =>
    {
        options.UseLocalServer();
        options.UseAspNetCore();
    });

// -----------------------------------------------------------------------------
// ASP.NET Core Authentication / Authorization
// -----------------------------------------------------------------------------

/// <summary>
/// Enables authentication using OpenIddict validation.
/// </summary>
builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme =
        OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;

    options.DefaultChallengeScheme =
        OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme;
});

/// <summary>
/// Enables authorization with a global fallback policy.
/// Default: all endpoints require authentication.
/// Guest access must be explicitly marked with [AllowAnonymous].
/// </summary>
builder.Services.AddAuthorization(options =>
{
    options.FallbackPolicy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
});

// -----------------------------------------------------------------------------
// HttpClient Factory
// -----------------------------------------------------------------------------

builder.Services.AddHttpClient();

// -----------------------------------------------------------------------------
// Dependency Injection (Application + Infrastructure)
// -----------------------------------------------------------------------------

/// <summary>
/// Registers application and infrastructure services.
/// </summary>
builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<ICommonService, CommonService>();
builder.Services.AddScoped<IHomeService, HomeService>();
builder.Services.AddScoped<ILayoutService, LayoutService>();
builder.Services.AddScoped<ILibraryService, LibraryService>();
builder.Services.AddScoped<IBookInfoService, BookInfoService>();
builder.Services.AddScoped<IWriterInfoService, WriterInfoService>();
builder.Services.AddScoped<IWriterService, WriterService>();
builder.Services.AddScoped<IWorkspaceService, WorkspaceService>();

builder.Services.AddScoped<IAuthRepository, AuthRepository>();
builder.Services.AddScoped<ICommonRepository, CommonRepository>();
builder.Services.AddScoped<IHomeRepository, HomeRepository>();
builder.Services.AddScoped<ILayoutRepository, LayoutRepository>();
builder.Services.AddScoped<ILibraryRepository, LibraryRepository>();
builder.Services.AddScoped<IBookInfoRepository, BookInfoRepository>();
builder.Services.AddScoped<IWriterInfoRepository, WriterInfoRepository>();
builder.Services.AddScoped<IWriterRepository, WriterRepository>();
builder.Services.AddScoped<IWorkspaceRepository, WorkspaceRepository>();

// -----------------------------------------------------------------------------
// Build Application
// -----------------------------------------------------------------------------

var app = builder.Build();

// -----------------------------------------------------------------------------
// OpenAPI + Scalar UI
// -----------------------------------------------------------------------------

app.MapOpenApi()
    .AllowAnonymous();

if (app.Environment.IsDevelopment())
{
    app.MapScalarApiReference()
        .AllowAnonymous();;
}

// -----------------------------------------------------------------------------
// Middlewares
// -----------------------------------------------------------------------------

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();

app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

// -----------------------------------------------------------------------------
// Endpoints
// -----------------------------------------------------------------------------

app.UseExceptionMiddleware();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});

// -----------------------------------------------------------------------------
// Run Application
// -----------------------------------------------------------------------------

app.Run();
