// -----------------------------------------------------------------------------
// <auto-generated>
//     This file provides the implementation for generating OpenIddict access
//     tokens by calling the /connect/token endpoint using HttpClient.
//     This is the recommended approach for OpenIddict 7.x.
// </auto-generated>
// -----------------------------------------------------------------------------

namespace TomatoNovel.Infrastructure.Services;

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using TomatoNovel.Application.Exceptions;
using TomatoNovel.Application.Interfaces;
using TomatoNovel.Application.DTOs.Auth.Responses;

public class OpenIddictTokenService : IOpenIddictTokenService
{
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly IConfiguration _configuration;

    public OpenIddictTokenService(
        IHttpClientFactory httpClientFactory,
        IConfiguration configuration)
    {
        _httpClientFactory = httpClientFactory;
        _configuration = configuration;
    }

    public async Task<string> GenerateTokenAsync(string username, string password)
    {
        if (string.IsNullOrWhiteSpace(username) ||
            string.IsNullOrWhiteSpace(password))
        {
            throw new BusinessException(
                50001,
                "Username or password is empty when requesting token.");
        }

        // ---------------------------------------------------------------------
        // 1️⃣ 创建 HttpClient
        // ---------------------------------------------------------------------
        var client = _httpClientFactory.CreateClient();

        var authority =
            _configuration["OpenIddict:Authority"]
            ?? throw new InvalidOperationException(
                "OpenIddict:Authority is not configured.");

        client.BaseAddress = new Uri(authority);

        // ---------------------------------------------------------------------
        // 2️⃣ 构造 Password Grant 请求
        // ---------------------------------------------------------------------
        var form = new Dictionary<string, string>
        {
            ["grant_type"] = "password",
            ["username"]   = username,
            ["password"]   = password,
            // ⚠️ scope 必须和 Server RegisterScopes 完全一致
            ["scope"]      = "openid offline_access onlinestudy_api.read"
        };

        // 可选：如果你关闭了 AcceptAnonymousClients
        var clientId = _configuration["OpenIddict:ClientId"];
        if (!string.IsNullOrWhiteSpace(clientId))
        {
            form["client_id"] = clientId;
        }

        var clientSecret = _configuration["OpenIddict:ClientSecret"];
        if (!string.IsNullOrWhiteSpace(clientSecret))
        {
            form["client_secret"] = clientSecret;
        }

        using var content = new FormUrlEncodedContent(form);

        // ---------------------------------------------------------------------
        // 3️⃣ 调用 /connect/token
        // ---------------------------------------------------------------------
        using var response = await client.PostAsync(
            "/connect/token",
            content);

        // ---------------------------------------------------------------------
        // 4️⃣ OpenIddict 错误响应处理
        // ---------------------------------------------------------------------
        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();

            throw new BusinessException(
                50002,
                $"OpenIddict token endpoint returned error: {errorBody}");
        }

        // ---------------------------------------------------------------------
        // 5️⃣ 解析 Token 响应（正确 & 稳定写法）
        // ---------------------------------------------------------------------
        var rawBody = await response.Content.ReadAsStringAsync();

        if (string.IsNullOrWhiteSpace(rawBody))
        {
            throw new BusinessException(
                50003,
                "OpenIddict returned empty token response.");
        }

        var tokenResponse = JsonSerializer.Deserialize<TokenResponseDto>(
            rawBody,
            new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            });

        if (tokenResponse == null ||
            string.IsNullOrWhiteSpace(tokenResponse.AccessToken))
        {
            throw new BusinessException(
                50003,
                $"OpenIddict returned an invalid token response. Raw body: {rawBody}");
        }

        return tokenResponse.AccessToken;
    }
}
