// -----------------------------------------------------------------------------
// <auto-generated>
//     This file contains the authentication controller, responsible for handling
//     login and automatic registration requests.
//     Token issuing is delegated to the application service layer.
// -----------------------------------------------------------------------------

namespace TomatoNovel.Api.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TomatoNovel.Api.Responses;
using TomatoNovel.Application.DTOs.Auth.Requests;
using TomatoNovel.Application.DTOs.Auth.Responses;
using TomatoNovel.Application.Interfaces;

/// <summary>
/// Provides authentication endpoints including login and automatic registration.
/// </summary>
[ApiController]
[Route("api/auth")]
public class AuthController : ControllerBase
{
    private readonly IAuthService _authService;

    public AuthController(IAuthService authService)
    {
        _authService = authService;
    }

    /// <summary>
    /// Logs the user in or registers a new user, then returns user info and access token.
    /// </summary>
    [HttpPost("login_or_register/pwd")]
    [AllowAnonymous]
    [ProducesResponseType(typeof(ApiResponse<LoginOrRegisterResponseDto>), StatusCodes.Status200OK)]
    public async Task<IActionResult> LoginOrRegister([FromBody] LoginOrRegisterRequestDto request)
    {
        if (request == null)
        {
            return Ok(ApiResponse<object>.Fail(
                40000,
                "Invalid request payload."));
        }

        try
        {
            // 统一入口：登录/自动注册 + 颁发 Token（OpenIddict 调用细节在 Service 内部完成）
            LoginOrRegisterResponseDto result =
                await _authService.LoginOrRegisterAsync(request);

            if (result.User == null)
            {
                return Ok(ApiResponse<object>.Fail(
                    40001,
                    "Login failed: user not found."));
            }

            return Ok(ApiResponse<LoginOrRegisterResponseDto>.Success(result));
        }
        catch (Exception ex)
        {
            // 保持你项目的风格：统一 200 + 业务码
            return Ok(ApiResponse<object>.Fail(
                40002,
                $"Login failed: {ex.Message}"));
        }
    }
}
