// -----------------------------------------------------------------------------
// <auto-generated>
//     This file contains the authentication controller, responsible for handling
//     login and automatic registration requests.
//     Token issuing is handled by OpenIddict (/connect/token).
// -----------------------------------------------------------------------------

namespace TomatoNovel.Api.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TomatoNovel.Api.Responses;
using TomatoNovel.Application.DTOs.Auth.Requests;
using TomatoNovel.Application.DTOs.Auth.Responses;
using TomatoNovel.Application.Interfaces;

[ApiController]
[Route("api/auth/login-or-register")]
[AllowAnonymous]
public class AuthController : ControllerBase
{
    private readonly IAuthService _authService;

    public AuthController(IAuthService authService)
    {
        _authService = authService;
    }

    /// <summary>
    /// Logs the user in or registers a new user, then returns user info.
    /// Token issuing is handled separately via OpenIddict.
    /// </summary>
    [HttpPost("pwd")]
    [ProducesResponseType(typeof(ApiResponse<LoginOrRegisterResponseDto>), StatusCodes.Status200OK)]
    public async Task<IActionResult> LoginOrRegister([FromBody] LoginOrRegisterRequestDto request)
    {
        if (request == null)
        {
            return Ok(ApiResponse<object>.Fail(
                40000,
                "Invalid request payload."));
        }

        try
        {
            // 统一入口：登录 / 自动注册（仅业务逻辑，不颁发 Token）
            LoginOrRegisterResponseDto result =
                await _authService.LoginOrRegisterAsync(request);

            if (result == null)
            {
                return Ok(ApiResponse<object>.Fail(
                    40001,
                    "Login failed: user not found."));
            }

            return Ok(ApiResponse<LoginOrRegisterResponseDto>.Success(result));
        }
        catch (Exception ex)
        {
            return Ok(ApiResponse<object>.Fail(
                40002,
                $"Login failed: {ex.Message}"));
        }
    }
}
